apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microvms.vvm.tvm.github.com
spec:
  group: vvm.tvm.github.com
  names:
    kind: MicroVM
    listKind: MicroVMList
    plural: microvms
    singular: microvm
    shortNames:
    - mvm
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - image
            properties:
              image:
                type: string
                description: "Container image for the VM"
              command:
                type: array
                items:
                  type: string
                description: "Command to run in the VM"
              cpu:
                type: integer
                format: int32
                minimum: 1
                default: 1
                description: "Number of vCPUs"
              memory:
                type: integer
                format: int32
                minimum: 128
                default: 512
                description: "Amount of memory in MB"
              snapshot:
                type: string
                description: "Name of the snapshot to restore from"
              mcpMode:
                type: boolean
                default: false
                description: "Enable MCP mode for the VM"
              persistentStorage:
                type: boolean
                default: false
                description: "Enable persistent storage for the VM"
          status:
            type: object
            properties:
              state:
                type: string
                enum:
                - Creating
                - Running
                - Error
                - Deleted
                description: "Current state of the VM"
              vmId:
                type: string
                description: "Unique identifier for the VM"
              hostPod:
                type: string
                description: "Pod hosting the VM"
              node:
                type: string
                description: "Node running the VM"
              lastActivity:
                type: string
                format: date-time
                description: "Timestamp of last activity"
              error:
                type: string
                description: "Error message if the VM is in an error state"
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.state
    - name: Node
      type: string
      jsonPath: .status.node
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp