apiVersion: vvm.tvm.github.com/v1alpha1
kind: MicroVM
metadata:
  name: example-vm
  namespace: default
spec:
  image: ubuntu:20.04
  cpu: 1
  memory: 512
  command: ["/bin/bash", "-c", "echo 'Hello from MicroVM' && sleep infinity"]
  mcpMode: true
  persistentStorage: false